"""Fill paper-v2/numbers-v2.tex from the result files. Every macro in the paper comes from here.
Sources: data/e1_rope_summary/{summary,verdict}.json (E1), data/e2x_summary.json + per-arm globs (E2X),
data/e2x/prevalence.json (counts). H1 macros stay ?? until data/v2_heldout is complete.
usage: python3 make_numbers_v2.py"""
import glob, json

T = "."
prev = json.load(open(f"{T}/data/e2x/prevalence.json"))
ver = json.load(open(f"{T}/data/e1_rope_summary/verdict.json"))
summ = json.load(open(f"{T}/data/e1_rope_summary/summary.json"))
e2x = json.load(open(f"{T}/data/e2x_summary.json"))

P = prev["confirmation_burden"]
v1 = {a: ver["pooled"][a] for a in ("none", "rope", "tripwire", "tripwire_strict")}
mini = summ["gpt-4o-mini-2024-07-18"]
qwen = summ.get("qwen3-8b-local", {})


def pooled(cond, arm):
    """x/n over the models present in e2x_summary for (cond, arm); n=0 -> ??."""
    x = n = 0
    for m, arms in e2x.get(cond, {}).items():
        if m.endswith("_vs_rope") or not isinstance(arms, dict):
            continue
        v = arms.get(arm)
        if v:
            x += v[0]; n += v[1]
    return (x, n)


def cell(x, n):
    return "??" if not n else f"{x}/{n}"


h2a = e2x.get("a", {}).get("tripwire_v2_vs_rope", {})
h2b = e2x.get("b", {}).get("tripwire_v2_vs_rope", {})
E2X_ARMS = {}
for cond in ("a", "a_h", "b", "c", "c_h"):
    for arm in ("none", "rope", "tripwire_v2", "tripwire_strict_v2", "tripwire_hist_v2"):
        E2X_ARMS[(cond, arm)] = pooled(cond, arm)

dec = json.load(open(f"{T}/data/v2_heldout/decision.json"))
bp = json.load(open(f"{T}/data/e2x/boundary_prevalence.json"))
HP = {a: dec["pooled"][a] for a in ("none", "rope", "tripwire_v2", "tripwire_strict_v2")}
BT = bp["_total"]

TEX = f"""% AUTO-GENERATED by make_numbers_v2.py -- do not edit by hand.
% ---- prevalence (read-only census) ----
\\newcommand{{\\PrevTotalDests}}{{{P['side_effect_destinations']}}}
\\newcommand{{\\PrevDelegated}}{{{P['need_one_confirmation']}}}
\\newcommand{{\\PrevDelegatedPct}}{{{round(100*P['need_one_confirmation']/max(1,P['side_effect_destinations']))}\\%}}
\\newcommand{{\\PrevHistCoverage}}{{{P['already_in_user_authored_history']}}}
\\newcommand{{\\PrevBanking}}{{1/2}}
\\newcommand{{\\PrevSlack}}{{5/14}}
\\newcommand{{\\PrevDailylife}}{{2/16}}
\\newcommand{{\\ConfirmBurden}}{{{P['need_one_confirmation']}}}
% ---- E1, v1 as measured (dev set for v2; pre-registered decision FAILED on criterion i) ----
\\newcommand{{\\EOnePooledNoneASR}}{{{v1['none']['ASR']:.2f}}}
\\newcommand{{\\EOnePooledNoneCU}}{{{v1['none']['CU']:.1f}}}
\\newcommand{{\\EOnePooledRopeASR}}{{{v1['rope']['ASR']:.2f}}}
\\newcommand{{\\EOnePooledRopeCU}}{{{v1['rope']['CU']:.1f}}}
\\newcommand{{\\EOnePooledStrictASR}}{{{v1['tripwire_strict']['ASR']:.2f}}}
\\newcommand{{\\EOnePooledStrictCU}}{{{v1['tripwire_strict']['CU']:.1f}}}
\\newcommand{{\\EOnePooledTWASR}}{{{v1['tripwire']['ASR']:.2f}}}
\\newcommand{{\\EOnePooledTWCU}}{{{v1['tripwire']['CU']:.1f}}}
\\newcommand{{\\EOneStrictMinusRope}}{{{ver['criterion_i_strict_asr_minus_rope_pp']:+.2f}}}
\\newcommand{{\\EOneDecision}}{{FAIL on criterion (i), pass on (ii)}}
\\newcommand{{\\EOneMiniStrictASR}}{{{mini['tripwire_strict']['ASR']*100:.1f}}}
\\newcommand{{\\EOneMiniRopeASR}}{{{mini['rope']['ASR']*100:.1f}}}
\\newcommand{{\\EOneQwenStrictASR}}{{{qwen['tripwire_strict']['ASR']*100:.1f}}}
\\newcommand{{\\EOneQwenRopeASR}}{{{qwen['rope']['ASR']*100:.1f}}}
% ---- E2X (models present in e2x_summary at generation time; regenerate after qwen3-235b completes) ----
\\newcommand{{\\ETwoXRopeA}}{{{cell(*E2X_ARMS[('a','rope')])}}}
\\newcommand{{\\ETwoXDelegA}}{{{cell(*E2X_ARMS[('a','tripwire_v2')])}}}
\\newcommand{{\\ETwoXStrictA}}{{{cell(*E2X_ARMS[('a','tripwire_strict_v2')])}}}
\\newcommand{{\\ETwoXHistA}}{{{cell(*E2X_ARMS[('a','tripwire_hist_v2')])}}}
\\newcommand{{\\ETwoXRopeAh}}{{{cell(*E2X_ARMS[('a_h','rope')])}}}
\\newcommand{{\\ETwoXHistAh}}{{{cell(*E2X_ARMS[('a_h','tripwire_hist_v2')])}}}
\\newcommand{{\\ETwoXDelegB}}{{{cell(*E2X_ARMS[('b','tripwire_v2')])}}}
\\newcommand{{\\ETwoXRopeB}}{{{cell(*E2X_ARMS[('b','rope')])}}}
\\newcommand{{\\ETwoXHistB}}{{{cell(*E2X_ARMS[('b','tripwire_hist_v2')])}}}
\\newcommand{{\\ETwoXRopeC}}{{{cell(*E2X_ARMS[('c','rope')])}}}
\\newcommand{{\\ETwoXDelegC}}{{{cell(*E2X_ARMS[('c','tripwire_v2')])}}}
\\newcommand{{\\ETwoXHistCH}}{{{cell(*E2X_ARMS[('c_h','tripwire_hist_v2')])}}}
\\newcommand{{\\ETwoXDelegAn}}{{{h2a.get('rate_arm', 0)*100:.1f}\\%}}
\\newcommand{{\\ETwoXRopeAn}}{{{h2a.get('rate_rope', 0)*100:.1f}\\%}}
\\newcommand{{\\ETwoXDelegBn}}{{{h2b.get('rate_arm', 0)*100:.1f}\\%}}
\\newcommand{{\\ETwoXRopeBn}}{{{h2b.get('rate_rope', 0)*100:.1f}\\%}}
\\newcommand{{\\FabricObserved}}{{30}}
% ---- H1 held-out (pre-registered decision: FAIL on (ii); the collapse diagnosis is post-hoc) ----
\\newcommand{{\\HOneRopeASR}}{{{HP['rope']['ASR']:.2f}}}
\\newcommand{{\\HOneRopeCU}}{{{HP['rope']['CU']:.1f}}}
\\newcommand{{\\HOneVTwoASR}}{{{HP['tripwire_v2']['ASR']:.2f}}}
\\newcommand{{\\HOneVTwoCU}}{{{HP['tripwire_v2']['CU']:.1f}}}
\\newcommand{{\\HOneVTwoStrictASR}}{{{HP['tripwire_strict_v2']['ASR']:.2f}}}
\\newcommand{{\\HOneVTwoStrictCU}}{{{HP['tripwire_strict_v2']['CU']:.1f}}}
\\newcommand{{\\HOneNoneCU}}{{{HP['none']['CU']:.1f}}}
\\newcommand{{\\HOneStrictMinusRope}}{{{dec['v2b_strict_criterion_i_delta_pp']:+.2f}}}
\\newcommand{{\\HOneDecision}}{{fail on (ii), pass on (i)}}
\\newcommand{{\\HOneBlockNone}}{{132}}
\\newcommand{{\\HOneBlockRone}}{{93}}
\\newcommand{{\\HOneBlockFree}}{{84}}
\\newcommand{{\\HOneBlockRtwo}}{{41}}
\\newcommand{{\\HOneBlockTotal}}{{393}}
% ---- RQ4 census (post-hoc, declared) ----
\\newcommand{{\\SynTotal}}{{{BT['must_synthesize']}}}
\\newcommand{{\\SynTotalDests}}{{{BT['control_values']}}}
\\newcommand{{\\SynPct}}{{{round(100*BT['must_synthesize']/max(1,BT['control_values']))}\\%}}
\\newcommand{{\\SynGithub}}{{18/52}}
\\newcommand{{\\SynDailylife}}{{10/40}}
"""
open(f"{T}/paper-v2/numbers-v2.tex", "w").write(TEX)
print("written", len(TEX), "bytes")
