"""results.json -> $TRIPWIRE_OUT/numbers.tex. Every number in the prose comes from a macro here.
Naming: \\<Set><Arm><Metric>, Set in {Q (qwen3-8b-local), F (six frontier pooled)}; rates printed
as percentages with one decimal unless noted.
"""
import json
import os

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # release root
OUT_DIR = os.environ.get("TRIPWIRE_OUT", os.path.join(HERE, "out"))
os.makedirs(OUT_DIR, exist_ok=True)
J = json.load(open(os.path.join(OUT_DIR, "results.json")))
ARM = {"tw_monitor": "None", "tripwire": "TW", "tw_nodeleg": "TWnodeleg", "tw_strict": "TWstrict",
       "spotlighting": "Spot", "repeat_user_prompt": "Sand", "tool_filter": "Filter", "melon": "Melon",
       "pi_detector": "PID", "tw_nocompact": "TWnocompact", "tw_notaint": "TWnotaint"}
SET = {"qwen3-8b-local": "Q", "qwen25-7b-local": "R", "llama31-8b-local": "L", "granite31-8b-local": "G", "six frontier models pooled": "F"}
out = []


def pct(x):
    return f"{100 * x:.1f}"


def mac(name, val):
    out.append(f"\\newcommand{{\\{name}}}{{{val}\\xspace}}")


for k, v in J.items():
    parts = [p.strip() for p in k.split("|")]
    if parts[0] in ("model", "suite", "src", "fp", "residual"):
        continue  # figure-only data
    if parts[0] in SET and len(parts) == 2:
        s, a = SET[parts[0]], ARM[parts[1]]
        mac(f"{s}{a}ASR", pct(v["asr"]))
        mac(f"{s}{a}ASRlo", pct(v["asr_lo"]))
        mac(f"{s}{a}ASRhi", pct(v["asr_hi"]))
        for m_ in ("ua", "ub"):
            if f"{m_}_lo" in v:
                mac(f"{s}{a}{m_.upper()}lo", pct(v[f"{m_}_lo"]))
                mac(f"{s}{a}{m_.upper()}hi", pct(v[f"{m_}_hi"]))
        mac(f"{s}{a}UA", pct(v["ua"]))
        mac(f"{s}{a}UB", pct(v["ub"]))
        mac(f"{s}{a}Natt", v["n_att"])
        mac(f"{s}{a}Nben", v["n_ben"])
        mac(f"{s}{a}Secs", f"{v['secs']:.1f}")
    elif parts[0] == "monitor":
        s = {"qwen3-8b-local": "Q", "qwen25-7b-local": "R", "llama31-8b-local": "L", "granite31-8b-local": "G"}.get(parts[1], "F")
        for kk, vv in v.items():
            mac(f"Mon{s}{kk.replace('_', '')}", vv)
        if v["vval"]:
            mac(f"Mon{s}valrecall", pct(v["vval_flag"] / v["vval"]))
        if v["ben"]:
            mac(f"Mon{s}benflagrate", pct(v["ben_flag"] / v["ben"]))
    elif parts[0] == "atk":
        mdl = {"qwen3-8b-local": "Q", "qwen25-7b-local": "R", "llama31-8b-local": "L", "granite31-8b-local": "G"}[parts[1]]
        knd = {"tool_knowledge": "TK", "injecagent": "IA", "important_instructions": "II"}[parts[2]]
        mac(f"Atk{mdl}{knd}{ARM[parts[3]]}ASR", pct(v[0]))
        mac(f"Atk{mdl}{knd}{ARM[parts[3]]}N", v[1])
    elif parts[0] in ("adapt", "abl"):
        nm = parts[0].capitalize() + parts[1].capitalize() + ARM[parts[2]]
        mac(nm + "ASR", pct(v[0]))
        mac(nm + "N", v[1])
        if len(v) > 2:
            mac(nm + "K", v[2])
    elif k == "overhead":
        mac("OvhTasks", v["tasks"])
        mac("OvhCalls", v["calls"])
        mac("OvhTaskMed", f"{v['task_med']:.2f}")
        mac("OvhTaskPninetyfive", f"{v['task_p95']:.2f}")
        mac("OvhCallMed", f"{v['call_med']:.2f}")
        mac("OvhCallPninetyfive", f"{v['call_p95']:.2f}")
    elif k == "extra":
        for kk, vv in v.items():
            mac(kk, vv)
    elif k.startswith("paired"):
        for kk, vv in v.items():
            mac(kk, vv)
dst = os.path.join(OUT_DIR, "numbers.tex")
open(dst, "w").write("% generated by make_numbers.py from results.json, do not edit\n" + "\n".join(out) + "\n")
print(len(out), "macros ->", dst)

# ---- Table: main comparison (RQ1 + RQ2 columns)
ORDER = ["tw_monitor", "spotlighting", "repeat_user_prompt", "tool_filter", "pi_detector", "melon", "tripwire"]
LABEL = {"tw_monitor": "No defense", "spotlighting": "Spotlighting", "repeat_user_prompt": "Sandwich",
         "tool_filter": "Tool filter", "pi_detector": "PI detector", "melon": "MELON", "tripwire": "TripWire (ours)",
         "tw_nodeleg": "TripWire w/o delegation", "tw_strict": "TripWire-strict"}
CALLS = {"tw_monitor": "0", "spotlighting": "0", "repeat_user_prompt": "0", "tool_filter": "1 per task",
         "pi_detector": "0 (classifier)", "melon": "1 per step + embeddings", "tripwire": "0"}
SETS = [("qwen3-8b-local", ("asr", "ua", "ub")), ("qwen25-7b-local", ("asr", "ua", "ub")),
        ("six frontier models pooled", ("asr", "ua", "ub"))]
SETS = [(k, c) for k, c in SETS if f"{k} | tripwire" in J]
BETTER = {"asr": min, "ua": max, "ub": max}
best = {}
for k, cols in SETS:
    for c in cols:
        vals = [J[f"{k} | {d}"][c] for d in ORDER if d != "tw_monitor" and f"{k} | {d}" in J and J[f"{k} | {d}"]["n_att"]]
        best[(k, c)] = BETTER[c](vals) if vals else None
rows = []
for d in ORDER:
    cells = []
    for k, cols in SETS:
        v = J.get(f"{k} | {d}")
        for c in cols:
            if not v or not v["n_att"]:
                cells.append("--")
                continue
            t = pct(v[c])
            t = f"\\textbf{{{t}}}" if d != "tw_monitor" and best[(k, c)] is not None and abs(v[c] - best[(k, c)]) < 1e-12 else t
            if c == "asr" and f"{c}_lo" in v:  # 95% cluster bootstrap interval under the point estimate
                t = f"\\makecell{{{t}\\\\[-1pt]{{\\tiny [{pct(v[c + '_lo'])}, {pct(v[c + '_hi'])}]}}}}"
            cells.append(t)
    name = f"\\textbf{{{LABEL[d]}}}" if d == "tripwire" else LABEL[d]
    rows.append(name + " & " + " & ".join(cells) + f" & {CALLS[d]} \\\\")
HEAD = {"qwen3-8b-local": "Qwen3-8B", "qwen25-7b-local": "Qwen2.5-7B", "six frontier models pooled": "Six frontier models"}
ncol = sum(len(c) for _, c in SETS)
hdr1 = " & " + " & ".join(f"\\multicolumn{{{len(c)}}}{{c}}{{{HEAD[k]}}}" for k, c in SETS) + " & \\\\"
rules, at = [], 2
for _, c in SETS:
    rules.append(f"\\cmidrule(lr){{{at}-{at + len(c) - 1}}}")
    at += len(c)
hdr2 = "Defense & " + " & ".join("ASR $\\downarrow$ & UA $\\uparrow$ & BU $\\uparrow$" for _ in SETS) + " & Calls $\\downarrow$ \\\\"
tab = ("% generated by make_numbers.py from results.json, do not edit\n\\begin{table*}[t]\n\\centering\n\\footnotesize\n"
       "\\caption{Attack success rate (ASR), utility under attack (UA) and benign utility (BU) of each baseline and of TripWire, in percent. TripWire-strict appears in Table~\\ref{tab:models}. "
       "The two Qwen models are the open-weight models on which attacks succeed most often. The frontier columns pool six frontier models. "
       "Small brackets give 95\\% cluster bootstrap intervals of the ASR. The last column counts model calls a defense adds on top of the agent. Bold marks the best defense in each metric column. "
       + ("A dash marks a defense that we run only on the other models." if any("--" in r for r in rows) else "") + "}\n"
       "\\label{tab:main}\n\\resizebox{\\linewidth}{!}{%\n\\begin{tabular}{@{}l" + "c" * ncol + "c@{}}\n\\toprule\n"
       + hdr1 + "\n" + "".join(rules) + "\n" + hdr2 + "\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}}\n\\end{table*}\n")
open(os.path.join(OUT_DIR, "tab_main.tex"), "w").write(tab)
print("wrote tab_main.tex", len(rows), "rows")

# ---- Table: per model (benign utility and ASR of the main arms)
MODELS_T = [("gpt-5.6-sol", "GPT-5.6-sol"), ("gemini-3.1-pro", "Gemini-3.1-pro"), ("claude-sonnet-5", "Claude-Sonnet-5"),
            ("deepseek-v4.1-flash", "DeepSeek-v4.1-flash"), ("kimi-k3", "Kimi-k3"), ("glm-5.3", "GLM-5.3"),
            ("qwen3-8b-local", "Qwen3-8B"), ("qwen25-7b-local", "Qwen2.5-7B"), ("llama31-8b-local", "Llama-3.1-8B"),
            ("granite31-8b-local", "Granite-3.1-8B")]
ARMS_T = ["tw_monitor", "tripwire", "tw_strict", "spotlighting", "repeat_user_prompt", "tool_filter", "pi_detector", "melon"]
rows = []
for m, nm in MODELS_T:
    if f"model | {m} | tripwire" not in J:
        continue
    cells = []
    for d in ARMS_T:
        v = J.get(f"model | {m} | {d}")
        cells.append(f"{pct(v['asr'])} / {pct(v['ub'])}" if v and v["n_att"] else "--")
    rows.append(nm + " & " + " & ".join(cells) + " \\\\")
tab = ("% generated by make_numbers.py from results.json, do not edit\n\\begin{table*}[t]\n\\centering\n\\footnotesize\n"
       "\\caption{Attack success rate and benign utility per model, in percent, written as ASR / BU. Each cell holds 194 attack runs and 97 benign runs, apart from a few runs that exceeded the context window." + (" A dash marks a defense not run on that model." if any("--" in r for r in rows) else "") + "}\n"
       "\\label{tab:models}\n\\resizebox{\\linewidth}{!}{%\n\\begin{tabular}{@{}l" + "c" * len(ARMS_T) + "@{}}\n\\toprule\nModel & "
       + " & ".join(LABEL[d] for d in ARMS_T) + " \\\\\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}}\n\\end{table*}\n")
open(os.path.join(OUT_DIR, "tab_models.tex"), "w").write(tab)
print("wrote tab_models.tex", len(rows), "rows")

for su_, f_ in J.get("fp", {}).items():
    out.append(f"\\newcommand{{\\FP{su_.capitalize()}Runs}}{{{f_.get('runs', 0)}\\xspace}}")
    out.append(f"\\newcommand{{\\FP{su_.capitalize()}N}}{{{f_.get('n', 0)}\\xspace}}")
open(dst, "w").write("% generated by make_numbers.py from results.json, do not edit\n" + "\n".join(out) + "\n")

# ---- Table: benign refusals and residual successes
fp = J.get("fp", {})
res = J.get("residual", {})
rows = []
for su in ("banking", "slack", "travel", "workspace"):
    f = fp.get(su, {})
    rq = res.get("qwen3-8b-local", {})
    rr = res.get("qwen25-7b-local", {})
    def r3(rq):
        return f"{rq.get(su + '|delegated', 0)} & {rq.get(su + '|environment', 0)} & {rq.get(su + '|nocontrol', 0)}"
    rows.append(f"{su.capitalize()} & {f.get('runs', 0)} / {f.get('n', 0)} & {f.get('AMBIGUOUS', 0)} & {f.get('FREE_TEXT', 0)} & {f.get('TRUST', 0)} & "
                + r3(rq) + " & " + r3(rr) + " \\\\")
tab = ("% generated by make_numbers.py from results.json, do not edit\n\\begin{table*}[t]\n\\centering\n\\footnotesize\n"
       "\\caption{Where TripWire errs, per suite. Left, benign runs of the six frontier models in which TripWire refused at least one call, "
       "with the label that caused the refusal. A run can carry more than one label. Right, attacks that still succeed under TripWire on the open-weight models, "
       "by cause. A delegated success takes its destination from a document the user named. Environment and no-control successes are outside the scope of TripWire.}\n"
       "\\label{tab:errors}\n\\setlength{\\tabcolsep}{9pt}\n\\resizebox{\\linewidth}{!}{%\n\\begin{tabular}{@{}lcccc|ccc|ccc@{}}\n\\toprule\n"
       " & \\multicolumn{4}{c|}{Benign runs with a refusal (frontier)} & \\multicolumn{3}{c|}{Qwen3-8B successes} & \\multicolumn{3}{c}{Qwen2.5-7B successes} \\\\\n"
       "Suite & runs & ambiguous & free text & trust level & delegated & environment & no control & delegated & environment & no control \\\\\n\\midrule\n"
       + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}}\n\\end{table*}\n")
open(os.path.join(OUT_DIR, "tab_errors.tex"), "w").write(tab)
print("wrote tab_errors.tex")

# paired differences TripWire minus no defense, with cluster bootstrap intervals over user tasks
P = J.get("paired", {})
rows = []
for lab, t in (("Qwen3-8B", "Q"), ("Qwen2.5-7B", "R"), ("Llama-3.1-8B", "L"), ("Granite-3.1-8B", "G"), ("Six frontier models", "F")):
    if f"Pair{t}SecN" not in P:
        continue
    cells = []
    for m in ("Sec", "UA", "UB"):
        k = f"Pair{t}{m}"
        cells.append(f"${P[k + 'D']}$ [${P[k + 'Dlo']}$, ${P[k + 'Dhi']}$] & ${P[k + 'P']}$")
    rows.append(f"{lab} & {P[f'Pair{t}SecN']} / {P[f'Pair{t}UBN']} & " + " & ".join(cells) + " \\\\")
tab = ("% generated by make_numbers.py from results.json, do not edit\n\\begin{table*}[t]\n\\centering\n\\footnotesize\n"
       "\\caption{Paired difference between TripWire and no defense on identical runs, in percentage points, with 95\\% "
       "cluster bootstrap intervals that resample user tasks. Negative values mean TripWire is lower. The p-values come from "
       "an exact McNemar test on the discordant pairs. Pairs counts attack pairs and benign tasks.}\n\\label{tab:paired}\n"
       "\\resizebox{\\linewidth}{!}{%\n\\begin{tabular}{@{}lccccccc@{}}\n\\toprule\n"
       " & & \\multicolumn{2}{c}{ASR $\\downarrow$} & \\multicolumn{2}{c}{UA $\\uparrow$} & \\multicolumn{2}{c}{BU $\\uparrow$} \\\\\n"
       "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}\n"
       "Model & Pairs & $\\Delta$ [95\\% CI] & $p$ & $\\Delta$ [95\\% CI] & $p$ & $\\Delta$ [95\\% CI] & $p$ \\\\\n\\midrule\n"
       + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}}\n\\end{table*}\n")
open(os.path.join(OUT_DIR, "tab_paired.tex"), "w").write(tab)
print("wrote tab_paired.tex")
